import { Metadata } from "next";
import { Provider } from "./provider";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head"; // Import next/head for adding elements to the <head>

const inter = Inter({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "R E R O U T E",
  description: "Generated by create next app",
  icons: {
	  icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}

